### ISSUE TITLE
tidy up the readme

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#119]
the home page has a few out of date things

Usage - Shape creation should include images and be renamed to something like Usage - parametric shape

Usage - Creating a Plasma should be renamed to something like this Usage - parametric shape creation

Import statement is wrong for the plasma

Usage - Reactor creation should include images and be changed to Usage - parametric reactor

the parametric reactor example uses add which no longer exists

utils.py should also be added to the "Core modules" section

Perhaps the long list of python classes could be removed from the index page

**Comment by billingsley-john** [comment]
Update - TODO:
Add parametric reactors section
utils.py should also be added to the "Core modules" section
Perhaps the long list of python classes could be removed from the index page
Add images to examples

**Comment by billingsley-john** [comment]
Update - TODO:
utils.py should also be added to the "Core modules" section
