### ISSUE TITLE
Wrong attributes in ITER divertor's doc

### ISSUE THREAD

**Issue by RemiTheWarrior** [ukaea/paramak#128]
https://github.com/ukaea/paramak/blob/0044d17ae7110661845817b78831fbc328e7dd88/paramak/parametric_components/divertor_ITER.py#L34-L55

Some of these attributes aren't actual attributes but rather the parameters. These should be corrected

**Comment by Shimwell** [comment]
Thanks @RemiTheWarrior looks good to me, if you are happy i shall merge this in

**Comment by RemiTheWarrior** [comment]
@Shimwell @billingsley-john this can be closed since it has been fixed in #129
