### ISSUE TITLE
A blanket which has a start and stop thickness

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#142]
All of the blankets are Constant Thicknesses which is great but occasionally there is a need for a variable thickness blanket

For example the EU DEMO blanket has a thicker outboard blanket than the inboard blanket https://images.app.goo.gl/5FCPGWVKosSfgJ7Z7

perhaps thickness could allow a list of two thickness and then linear interpolation between the 2 points or a start_thickness and stop_thickness could be used instead

**Comment by Shimwell** [comment]
Perhaps a variable offset from the plasma as well

**Comment by RemiTheWarrior** [comment]
@Shimwell How about a component with thickness distribution along the poloidal section ?

**Comment by Shimwell** [comment]
Yes that sounds even better

**Comment by RemiTheWarrior** [comment]
@Shimwell well in that case this can be achieved by adapting the current blanket and allow the thickness argument to be a callable (a function of poloidal angle).

**Comment by Shimwell** [comment]
this would be super flexible, perhaps a bit harder for the user compared to just two numbers [start_thicknes, stop_thickness]

**Comment by RemiTheWarrior** [comment]
as often: why not do both ?
The thickness parameter can be a float (constant thickness), a tuple of 2 floats (thickness varying linearly between start_thickness and stop_thickness), or a callable (function of angle).

**Comment by Shimwell** [comment]
That would be the ultimate solution.

**Comment by RemiTheWarrior** [comment]
This would be needed if a user would want to make this kind of blanket
![image](https://user-images.githubusercontent.com/40028739/89264953-13612b00-d634-11ea-9709-5a6eafc43956.png)

**Comment by RemiTheWarrior** [comment]
Done in #158 this can be closed
