### ISSUE TITLE
Read the docs for main branch

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#153]
We have a read the docs for the develop branch call latest but nothing for the stable version

Perhaps we should introduce another readthedocs version

**Comment by billingsley-john** [comment]
Documentation for main branch added to ReadtheDocs. Default landing page for docs changed to main.

**Comment by billingsley-john** [comment]
Need to check how this documentation rebuilds when commits are made to repository

**Comment by Shimwell** [comment]
We can check this during the weekly merge to main on Friday :-)

**Comment by Shimwell** [comment]
This has now been done and two versions are availabe
https://paramak.readthedocs.io/en/latest/
https://paramak.readthedocs.io/en/main/
