### ISSUE TITLE
New neutronics workflow

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#154]
There is an option to have an open source method of making h5m dagmc files.

Here is a demo

https://gist.github.com/pshriwise/52452c37d4b7dd89bdc9374e13c35157

If this were to be implemented we would need to ensure the STL geometry does not overlap on the curves. This could perhaps be done by adding lots of control points to the geometry

**Comment by RemDelaporteMathurin** [comment]
@Shimwell, I think h5m files are now implemented. Can this be closed ?
