### ISSUE TITLE
make_faceted_neutronics_model.py script error

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#186]
find_number_of_volumes_in_each_step_file() function cannot be split over lines, must be one complete line

CURRENT:

geometry_details = find_number_of_volumes_in_each_step_file(
[indent] geometry_details, str(os.path.abspath("."))
)

FIX TODO:

geometry_details = find_number_of_volumes_in_each_step_file(geometry_details, str(os.path.abspath(".")))

**Comment by Shimwell** [comment]
Ah I'm sorry this is probably my fault running the pep8 processor over the whole code base. We can revert these two Trelis scripts

**Comment by billingsley-john** [comment]
Script requires line continuation character ("\") to be explicitly specified for trelis

**Comment by billingsley-john** [comment]
autopep8 removes newline characters, so this is not a viable solution

**Comment by billingsley-john** [comment]
the argument --exclude="make_faceteted_neutronics_model.py" can be used locally to ignore the trelis script, however, this does not seem to work when added to the autopep8.yml file.

**Comment by billingsley-john** [comment]
Resolved across #188, #189, #191, and #193.

yml file required --exclude=make_faceteted_neutronics_model.py (i.e. without " ")
