### ISSUE TITLE
Princeton-D TF coil

### ISSUE THREAD

**Issue by RemiTheWarrior** [ukaea/paramak#205]
Thanks to the system of differential equations described [here](https://repository.lib.ncsu.edu/bitstream/handle/1840.20/27004/N2.1-6.pdf?sequence=1), Princeton-D TF coils can be added to the Paramak.

**Comment by RemiTheWarrior** [comment]
@Shimwell @billingsley-john what do you think the input parameters should be ?

**Comment by RemiTheWarrior** [comment]
![image](https://user-images.githubusercontent.com/40028739/91277199-caa81800-e782-11ea-935b-6fbc1433d595.png)
So far 2 input parameters must be chosen out of 3 which are R1 (orange line), R2 (green line) and R0 (red line).

**Comment by Shimwell** [comment]
Super, 3 radial build parameters, I guess the red one can be chosen to match the plasma major radius
Does the thickness of the coil feature as a parameter

**Comment by RemiTheWarrior** [comment]
Well we need to choose 2 of these 3 parameters and the third one will be computed based on the two others.

Yes the thickness of the coil is a parameter see #207

**Comment by RemiTheWarrior** [comment]
Resolved in #207
