### ISSUE TITLE
pypi rebuilding

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#233]
The pypi package is rebuild when a PR is made to the main branch. Subsequent changes to the PR (changes to develop branch) cause pypi package to rebuild, however, rebuild fails because we already have a build of the same version number. Therefore, subsequent changes to the PR are not incorporated into the pypi package. 
Would it be better to only rebuild the pypi package once the PR has been merged? I.e. pypi package rebuild on commits to main, rather than PR's to main?

**Comment by Shimwell** [comment]
I think the git actions now rebuilds PyPi when merging into main

Also we have to manually bump the version number.

I think the manual bump is fine as sometimes we want a minor or major bump and automatically this would only ever be minor
