### ISSUE TITLE
Varible offset for blanket

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#251]
To reproduce geometry relevant for EU DEMO designs the blankets need a little more flexibility.

In this case it looks like a variable offset from the plasma is needed to match the EU DEMO blanket shape

![Screenshot from 2020-09-15 21-49-48](https://user-images.githubusercontent.com/8583900/93271051-4279c900-f7aa-11ea-9940-dfd355f81929.png)

The segmentation of the blanket is looking better and an example has been added to the example_parametric_components branch. https://github.com/ukaea/paramak/blob/demo/examples/example_parametric_components/make_demo_style_blankets.py
Eventually this can be part of a demo model

![Screenshot from 2020-09-15 23-21-13](https://user-images.githubusercontent.com/8583900/93271197-92f12680-f7aa-11ea-88cd-9a67f925fda3.png)
![Screenshot from 2020-09-15 23-21-22](https://user-images.githubusercontent.com/8583900/93271200-94225380-f7aa-11ea-8de9-46f9dfa07d52.png)

**Comment by RemiTheWarrior** [comment]
@Shimwell the shape of the DEMO blanket you're showing kinda looks like the princeton D shape (with a straight end on the inner side). Are you sure that a variable offset would change that ?
Does tweaking the shaping parameters (triangularity and so on) help ?

**Comment by Shimwell** [comment]
Variable offset implemented, I shall have another go at the demo blanket soon
