### ISSUE TITLE
html graph plotting

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#252]
Currently, html graphs are plotted with straight lines between each point. Last point=first point is appended to self.points which facilitates straight line between [-1] point and last point but prevents the hovertext for first point being seen. At some point, it would be better to join the points by connection type instead of straight lines. Also worth considering whether last point=first point needs to be added to self.points?

**Comment by RemDelaporteMathurin** [comment]
is this a doublon of #84 ?
