### ISSUE TITLE
single null ball reactor components

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#269]
Some components of the single null ball reactor are sometimes not created successfully, but no error is raised. This only happens occasionally and construction is sometimes successful. The submersion ball reactor seems to be more stable as this error doesn't seem to occur, so it may be better to structure the ball reactor construction like the submersion ball reactor

**Comment by Shimwell** [comment]
Single null ball reactor has been rewritten in #317 
Hopefully this write solves it but if not we can reopen
