### ISSUE TITLE
Helper points on ToroidalFieldCoilPrincetonD

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#274]
When making a ToroidalFieldCoilPrincetonD it makes a nice outer TF coil hoop. 

Users must then make an inner tf coil leg. It would therefore be useful if the coordinates of the points where inner tf leg connects are more accessible from the ToroidalFieldCoilPrincetonD

If the coordinates of the green patch on this diagram were available as attributes on the instance of the class than that would be great

Something like this 

```
my_outer_tf = ToroidalFieldCoilPrincetonD(random args)
print(my_outer_tf.inner_leg_connection_points)
> [(300, 400), (300, -400), (350, -400), (350, 400)]
```

![Screenshot from 2020-09-21 22-26-48](https://user-images.githubusercontent.com/8583900/93823607-ff13d480-fc59-11ea-97ce-2f881fb67eb3.png)

**Comment by RemiTheWarrior** [comment]
@Shimwell I think this is already given for the Triple Arc magnet. I shall try and have a look a the PrincetonD class

**Comment by Shimwell** [comment]
Thanks for fixing this Remi
