### ISSUE TITLE
BlanketFP offset_from_plasma not working when plasma not provided

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#283]
when using the BlanketFP with an offset_from_plasma it is sometimes ignored

When providing plasma=plasma to the BlanketFP then the offset works

However when providing the same plasma in terms of minor radius elongation and triangulation it appears to ignore the offset from plasma argument

Ignores offset
```
import paramak
plasma = paramak.Plasma(
             minor_radius=150.0,
             major_radius=450.0,
             triangularity=0.55,
             elongation=2.0,
             rotation_angle=180
)
plasma.export_stp('plasma.stp')

blanket = paramak.BlanketFP(
    minor_radius=150.0,
    major_radius=450.0,
    triangularity=0.55,
    elongation=2.0,
    thickness=100,
    offset_from_plasma=25,
    start_angle=-160,
    stop_angle=160,
    rotation_angle=180
)
blanket.export_stp('blanket_broken.stp')
```

![Screenshot from 2020-09-23 01-11-39](https://user-images.githubusercontent.com/8583900/93950079-702ab900-fd3a-11ea-8367-82e4a3404a9e.png)

while this appears to take the offset_from_plasma into account
```
plasma = paramak.Plasma(
             minor_radius=150.0,
             major_radius=450.0,
             triangularity=0.55,
             elongation=2.0,
             rotation_angle=180
)
plasma.export_stp('plasma.stp')

blanket = paramak.BlanketFP(
    plasma=plasma,
    thickness=100,
    offset_from_plasma=25,
    start_angle=-160,
    stop_angle=160,
    rotation_angle=180
)
blanket.export_stp('blanket_working.stp')
```
![Screenshot from 2020-09-23 01-11-08](https://user-images.githubusercontent.com/8583900/93950098-7f116b80-fd3a-11ea-8e3c-06a81adcd985.png)

**Comment by RemiTheWarrior** [comment]
I'm on it

**Comment by Shimwell** [comment]
Thanks for fixing this, I've tested and can confirm it works as hoped
