### ISSUE TITLE
new parametric shape for ports request

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#297]
To make a nice DEMO model we will need ports

Something like this so we can cut them from the blanket

![image](https://user-images.githubusercontent.com/8583900/94254610-f142a580-ff1e-11ea-978b-ab62e659861a.png)

**Comment by Shimwell** [comment]
I can do this next week

**Comment by RemDelaporteMathurin** [comment]
@Shimwell this has been fixed in #337. Closing this
