### ISSUE TITLE
tf coil workplanes

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#308]
workplane = "XY" causes incorrect iterable azimuthal placements

**Comment by billingsley-john** [comment]
Some workplanes cause the azimuthal placements of each solid to occur in the 'incorrect' plane

**Comment by RemDelaporteMathurin** [comment]
Is this because this line should depend on the workplane ?
https://github.com/ukaea/paramak/blob/23d50e9a81c1be846016dba106c8f6590308f78e/paramak/shape.py#L439

**Comment by Shimwell** [comment]
Perhaps related to #312 and therefore solved by #428 thanks to Remi

**Comment by RemDelaporteMathurin** [comment]
I think this can be closed now
