### ISSUE TITLE
Diagram with labels for ToroidalFieldCoilPrincetonD

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#310]
Adding images to ToroidalFieldCoilPrincetonD

We could do with some labels to explain R1 and R2 parameters in the [Mathcha](https://www.mathcha.io/editor) diagrams 

I have started the diagrams but am not quite sure where R1 and R2 go, any hints @RemiTheWarrior 

Also I added a create_solid method to the ToroidalFieldCoilPrincetonD so that the innerleg can be made, hence the diagram includes the inner leg

![Screenshot from 2020-09-28 20-57-40](https://user-images.githubusercontent.com/8583900/94479849-4b689280-01cd-11eb-9654-88fd9a91e81a.png)
![Screenshot from 2020-09-28 20-57-30](https://user-images.githubusercontent.com/8583900/94479853-4c012900-01cd-11eb-9b59-0fcd5f4dc531.png)

**Comment by RemiTheWarrior** [comment]
![image](https://user-images.githubusercontent.com/40028739/94526318-a930c500-0235-11eb-85c9-28cbe3ee08b0.png)
I apologise for the poor quality of this diagram 😄

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-29 08-57-08](https://user-images.githubusercontent.com/8583900/94529559-cd8aa280-0231-11eb-9919-48d3c642a5d7.png)

Thanks for the hints @RemiTheWarrior I shall update the docs soon

**Comment by RemiTheWarrior** [comment]
@Shimwell you're very welcome. What about placing the origin as well ?
