### ISSUE TITLE
Images for the documentation and Readme

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#32]
The images which are currently hosted on google drive and are not loading up every time the Readme is loaded.

Remi has shown us another way using github issues to host images which we can try :-)

![process](https://user-images.githubusercontent.com/8583900/86237158-2abf7b00-bb93-11ea-9a78-a987f20359a3.png)
![process_submersion](https://user-images.githubusercontent.com/8583900/86237161-2b581180-bb93-11ea-99ff-01cc1cec62ef.png)
![demo17](https://user-images.githubusercontent.com/8583900/86237165-2c893e80-bb93-11ea-8fcd-838eb3180c95.png)

color scheme uses https://colorbrewer2.org/#type=qualitative&scheme=Set1&n=8

**Comment by Shimwell** [comment]
![3d](https://user-images.githubusercontent.com/8583900/86237379-90136c00-bb93-11ea-80fb-54e2dab74819.gif)

**Comment by billingsley-john** [comment]
![blanket_constant_thickness](https://user-images.githubusercontent.com/56687624/86241428-c56f8800-bb9a-11ea-9d97-d45ff7089f92.png)
![center_column_shield_cylinder](https://user-images.githubusercontent.com/56687624/86241438-caccd280-bb9a-11ea-9548-b199759a6dbc.png)
![center_column_shield_flat_top_hyperbola](https://user-images.githubusercontent.com/56687624/86241446-cdc7c300-bb9a-11ea-8310-d54397338da8.png)
![center_column_shield_hyperbola](https://user-images.githubusercontent.com/56687624/86241456-d0c2b380-bb9a-11ea-9728-88fe4081345f.png)
![center_column_shield_plasma_hyperbola](https://user-images.githubusercontent.com/56687624/86241464-d3bda400-bb9a-11ea-83b4-a3ff0bf630c4.png)
![inner_tf_coils_circular](https://user-images.githubusercontent.com/56687624/86241469-d9b38500-bb9a-11ea-935f-8644fa01ab8c.png)
![inner_tf_coils_flat](https://user-images.githubusercontent.com/56687624/86241472-db7d4880-bb9a-11ea-8fb9-325b3342fe11.png)
![plasma_shape](https://user-images.githubusercontent.com/56687624/86241481-dddfa280-bb9a-11ea-95c7-408c935c6763.png)
![poloidal_field_coil](https://user-images.githubusercontent.com/56687624/86241487-dfa96600-bb9a-11ea-96ba-54f22ecef1ef.png)
![poloidal_field_coil_case](https://user-images.githubusercontent.com/56687624/86241492-e1732980-bb9a-11ea-9331-586a39d32cfb.png)

**Comment by Shimwell** [comment]
![extruded_circle](https://user-images.githubusercontent.com/8583900/86246768-6feba900-bba3-11ea-81a8-0d77a843b943.png)
![extruded_mixed](https://user-images.githubusercontent.com/8583900/86246772-711cd600-bba3-11ea-9d98-4af6a4427222.png)
![extruded_splines](https://user-images.githubusercontent.com/8583900/86246774-71b56c80-bba3-11ea-94cb-d2496365ff18.png)
![extruded_straights](https://user-images.githubusercontent.com/8583900/86246776-724e0300-bba3-11ea-91c9-0fd239225206.png)
![rotated_circle](https://user-images.githubusercontent.com/8583900/86246778-72e69980-bba3-11ea-9b33-d74e2c2d084b.png)
![rotated_mixed](https://user-images.githubusercontent.com/8583900/86246781-737f3000-bba3-11ea-847c-38c94e4a65d7.png)
![rotated_splines](https://user-images.githubusercontent.com/8583900/86246785-7548f380-bba3-11ea-90b7-03249be41a00.png)
![rotated_straights](https://user-images.githubusercontent.com/8583900/86246786-767a2080-bba3-11ea-90e7-22d816690caa.png)

**Comment by RemiTheWarrior** [comment]
Hi all, you don't even have to create the whole issue.
Just open a new one, copy paste your image, copy the URL in your readme, cancel the issue.

**Comment by Shimwell** [comment]
![rotated_mixed](https://user-images.githubusercontent.com/8583900/86258771-17240c80-bbb3-11ea-990f-e87de26b1589.png)
![extrude_mixed](https://user-images.githubusercontent.com/8583900/86259588-1b045e80-bbb4-11ea-9360-7d82492b9dde.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-01 16-16-01](https://user-images.githubusercontent.com/8583900/86261239-34a6a580-bbb6-11ea-812c-ac6fa6a8f0e2.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-02 14-30-23](https://user-images.githubusercontent.com/8583900/86364843-a04d4900-bc70-11ea-9972-92c3761b56bf.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-02 14-32-19](https://user-images.githubusercontent.com/8583900/86365020-dee30380-bc70-11ea-8258-5e591c6c3235.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-02 14-51-01](https://user-images.githubusercontent.com/8583900/86367107-7c3f3700-bc73-11ea-9ab1-075a8401b0d3.png)
CenterColumnShieldCircular

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-02 14-54-25](https://user-images.githubusercontent.com/8583900/86367515-f7a0e880-bc73-11ea-804c-e55472a8d045.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-04 20-31-36](https://user-images.githubusercontent.com/8583900/86519778-32eb1500-be36-11ea-9794-0383b66624c5.png)

blanket constant thickness horizontal ends

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-07 18-57-02](https://user-images.githubusercontent.com/8583900/86822598-bcdbed80-c083-11ea-820e-f6c13d639170.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-07-08 13-22-40](https://user-images.githubusercontent.com/56687624/86918503-bb133800-c11e-11ea-8bd1-9af10b68a33f.png)
![Screenshot from 2020-07-08 13-23-22](https://user-images.githubusercontent.com/56687624/86918512-bd759200-c11e-11ea-912b-93549c570def.png)
![Screenshot from 2020-07-08 13-25-33](https://user-images.githubusercontent.com/56687624/86918521-bfd7ec00-c11e-11ea-8420-3ef68976dcf6.png)
![Screenshot from 2020-07-08 13-26-33](https://user-images.githubusercontent.com/56687624/86918524-c1091900-c11e-11ea-9f98-fc88a910f67c.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-07-08 14-47-22](https://user-images.githubusercontent.com/56687624/86926474-04b55000-c12a-11ea-8070-df52687f2d8f.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-07-08 14-49-59](https://user-images.githubusercontent.com/56687624/86926740-565dda80-c12a-11ea-90c3-860dbb6b9332.png)

**Comment by billingsley-john** [comment]
![parametric_shapes](https://user-images.githubusercontent.com/56687624/87046793-81f7c800-c1f1-11ea-94c1-4c447bb18ff4.gif)

**Comment by billingsley-john** [comment]
Adding new images of parametric_shapes which are all approximately the same size. This makes it easier to create gifs and size tables correctly

![rotate_straight](https://user-images.githubusercontent.com/56687624/87055469-4f070180-c1fc-11ea-9679-a29e37a90e15.png)
![rotate_spline](https://user-images.githubusercontent.com/56687624/87055473-50382e80-c1fc-11ea-95dd-b4932b1e78d9.png)
![rotate_mixed](https://user-images.githubusercontent.com/56687624/87055483-53cbb580-c1fc-11ea-878d-92835684c8ff.png)
![rotate_circle](https://user-images.githubusercontent.com/56687624/87055489-54fce280-c1fc-11ea-9545-a61582aea20a.png)
![extrude_straight](https://user-images.githubusercontent.com/56687624/87055493-56c6a600-c1fc-11ea-8c58-f5b62ae72e0e.png)
![extrude_spline](https://user-images.githubusercontent.com/56687624/87055500-58906980-c1fc-11ea-879c-9f1845be3b57.png)
![extrude_mixed](https://user-images.githubusercontent.com/56687624/87055511-59c19680-c1fc-11ea-8740-8c7987745c45.png)
![extrude_circle](https://user-images.githubusercontent.com/56687624/87055517-5b8b5a00-c1fc-11ea-83ef-d4329c6815f7.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-07-09 16-09-44](https://user-images.githubusercontent.com/56687624/87058930-998a7d00-c200-11ea-846e-4084dbf82748.png)
![Screenshot from 2020-07-09 16-11-05](https://user-images.githubusercontent.com/56687624/87058944-9e4f3100-c200-11ea-8bd3-669b3705c179.png)
![Screenshot from 2020-07-09 16-20-44](https://user-images.githubusercontent.com/56687624/87059002-ae671080-c200-11ea-8275-91ef6ba5d4f9.png)

**Comment by billingsley-john** [comment]
![can_reactor](https://user-images.githubusercontent.com/56687624/87060447-74970980-c202-11ea-8720-403c24dbabcc.gif)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-09 19-10-46](https://user-images.githubusercontent.com/8583900/87075236-f04f8100-c217-11ea-9ffa-4791b722b9e7.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-12 20-18-48](https://user-images.githubusercontent.com/8583900/87254778-fe520b80-c47c-11ea-845f-470991d74874.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-13 15-31-28](https://user-images.githubusercontent.com/8583900/87316638-f39b8300-c51d-11ea-918b-5194d600d068.png)
new plasma

**Comment by billingsley-john** [comment]
Updated sweep shapes 

![9_new](https://user-images.githubusercontent.com/56687624/88060232-e0ac3280-cb5d-11ea-8bfe-b1db5f89a0d4.png)
![10_new](https://user-images.githubusercontent.com/56687624/88060236-e275f600-cb5d-11ea-87c3-330272a75904.png)
![11_new](https://user-images.githubusercontent.com/56687624/88060240-e43fb980-cb5d-11ea-8a9f-e652a7d51224.png)
![12_new](https://user-images.githubusercontent.com/56687624/88060245-e570e680-cb5d-11ea-8064-5f45798879e1.png)

**Comment by billingsley-john** [comment]
![6_new](https://user-images.githubusercontent.com/56687624/88060298-f7528980-cb5d-11ea-8e09-76c7b8171e83.png)

better extrude sweep shape

**Comment by billingsley-john** [comment]
![all_parametric_shapes](https://user-images.githubusercontent.com/56687624/88062079-3e417e80-cb60-11ea-8db1-f848ea5eb400.gif)

**Comment by RemiTheWarrior** [comment]
![image](https://user-images.githubusercontent.com/40028739/88180936-626b9100-cc2e-11ea-92df-1bac68b11e3b.png)

**Comment by RemiTheWarrior** [comment]
![image](https://user-images.githubusercontent.com/40028739/88182309-5254b100-cc30-11ea-94ba-296aae346032.png)

**Comment by billingsley-john** [comment]
![blanket_arc_h_new](https://user-images.githubusercontent.com/56687624/88293663-38c86d80-ccf3-11ea-9bfa-c166fc99c52c.png)
![blanket_arc_v_new](https://user-images.githubusercontent.com/56687624/88293666-39f99a80-ccf3-11ea-8c8d-84275fd0e0ce.png)
![center_column_circular_new](https://user-images.githubusercontent.com/56687624/88293672-3b2ac780-ccf3-11ea-9907-b1c8fd1ba0f0.png)
![center_column_cylinder_new](https://user-images.githubusercontent.com/56687624/88293674-3c5bf480-ccf3-11ea-8197-8db75358ff36.png)
![center_column_shield_flat_top_circular_new](https://user-images.githubusercontent.com/56687624/88293678-3d8d2180-ccf3-11ea-97f7-da9a46beddbf.png)
![center_column_shield_flat_top_hyperbola_new](https://user-images.githubusercontent.com/56687624/88293680-3ebe4e80-ccf3-11ea-8603-b7a290e6bfb4.png)
![center_column_shield_hyperbola_new](https://user-images.githubusercontent.com/56687624/88293688-40881200-ccf3-11ea-8b83-f18ffb062dd9.png)
![inner_tf_coils_circular_new](https://user-images.githubusercontent.com/56687624/88293695-41b93f00-ccf3-11ea-9ea8-338a64bb5566.png)
![inner_tf_coils_flat_new](https://user-images.githubusercontent.com/56687624/88293697-42ea6c00-ccf3-11ea-9e92-dc698813f1ee.png)
![pf_coil_case_new](https://user-images.githubusercontent.com/56687624/88293700-441b9900-ccf3-11ea-8be2-f6244fd71ffe.png)
![pf_coil_new](https://user-images.githubusercontent.com/56687624/88293704-44b42f80-ccf3-11ea-8194-f601e37a4b54.png)

**Comment by billingsley-john** [comment]
![BallReactor_new](https://user-images.githubusercontent.com/56687624/88823926-8e05f280-d1bd-11ea-8758-c79b49a8c5ac.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-07-29 17-25-57](https://user-images.githubusercontent.com/56687624/88826475-b4795d00-d1c0-11ea-992e-5a93aa6a0e15.png)

**Comment by Shimwell** [comment]
![neutronics_models_drawn_as_lines](https://user-images.githubusercontent.com/8583900/88866536-e57a8180-d202-11ea-8e3f-2662973c6f69.gif)
![Screenshot from 2020-07-30 00-05-52](https://user-images.githubusercontent.com/8583900/88866552-f1664380-d202-11ea-83ec-6891f2774e02.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-07-30 12-49-30](https://user-images.githubusercontent.com/56687624/88921452-79ca0000-d266-11ea-9f8f-5247e88b03cf.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-07-30 15-33-59](https://user-images.githubusercontent.com/56687624/88935871-1ea20880-d27a-11ea-82e1-1afa55ff9ba8.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-08-03 11-54-47](https://user-images.githubusercontent.com/8583900/89175754-477b1400-d580-11ea-9bba-3948e51a1705.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-08-03 12-21-05](https://user-images.githubusercontent.com/56687624/89177715-f79e4c00-d583-11ea-9445-fa6205757056.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-08-03 17-10-20](https://user-images.githubusercontent.com/56687624/89203299-465fdc00-d5ac-11ea-8663-a5b7eecfb584.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-08-05 12-18-42](https://user-images.githubusercontent.com/8583900/89407027-fb61d800-d715-11ea-892a-59283742687f.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-08-05 13-07-54](https://user-images.githubusercontent.com/8583900/89411100-c0af6e00-d71c-11ea-8d6a-cef2558b82dd.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-08-05 14-29-00](https://user-images.githubusercontent.com/8583900/89423931-070dc880-d72f-11ea-8cb3-1ce3ce840b7e.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-08-25 16-26-17](https://user-images.githubusercontent.com/56687624/91280434-a8ac9680-e77e-11ea-8c1a-28a662d1be29.png)
![Screenshot from 2020-08-25 16-28-33](https://user-images.githubusercontent.com/56687624/91280446-ab0ef080-e77e-11ea-8792-71b44a38b070.png)
![Screenshot from 2020-08-25 16-34-31](https://user-images.githubusercontent.com/56687624/91280450-ac401d80-e77e-11ea-8099-9292e4bb42e7.png)
![Screenshot from 2020-08-25 16-32-06](https://user-images.githubusercontent.com/56687624/91280475-b104d180-e77e-11ea-96ff-0bfcf8b8d5a9.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-08-26 12-39-40](https://user-images.githubusercontent.com/56687624/91299260-3e551f80-e799-11ea-82dc-1b300d3fbe45.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-09-02 12-47-27](https://user-images.githubusercontent.com/56687624/91977407-871d5300-ed1a-11ea-91e5-922e5c9b31a0.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-09-03 14-50-11](https://user-images.githubusercontent.com/56687624/92124454-b654c280-edf5-11ea-96d2-c0957f37a733.png)
triple arc

**Comment by billingsley-john** [comment]
![Screenshot from 2020-09-03 14-55-30](https://user-images.githubusercontent.com/56687624/92124475-bd7bd080-edf5-11ea-9c49-1db6422d77a0.png)
princeton plasma d

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-11 15-44-51](https://user-images.githubusercontent.com/8583900/92939579-de6fa180-f445-11ea-83b9-6f9f3260ac82.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-11 15-56-25](https://user-images.githubusercontent.com/8583900/92940739-61452c00-f447-11ea-90f2-a8ffa495da6c.png)

**Comment by Shimwell** [comment]
![demo_segment_blanket](https://user-images.githubusercontent.com/8583900/93619812-02e0f600-f9d1-11ea-903c-913c8bcb0f1b.png)

**Comment by Shimwell** [comment]
![plasmas](https://user-images.githubusercontent.com/8583900/93624384-2e1b1380-f9d8-11ea-99d1-9bf9e4e5b838.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-18 18-53-20](https://user-images.githubusercontent.com/8583900/93629472-47c05900-f9e0-11ea-8219-bc9d2c3e7f7c.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-21 19-39-44](https://user-images.githubusercontent.com/8583900/93807581-bc92cd80-fc42-11ea-8522-7fe14287b3c4.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-21 20-17-04](https://user-images.githubusercontent.com/8583900/93811079-84da5480-fc47-11ea-9c6c-7fd132f6d72d.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-22 15-53-38](https://user-images.githubusercontent.com/8583900/93908750-e86f8b00-fcf6-11ea-938e-349dd09e5915.png)

**Comment by Shimwell** [comment]
![firstwalls](https://user-images.githubusercontent.com/8583900/94197757-219e2b80-feae-11ea-8e41-0786d56c8b66.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-24 23-06-43](https://user-images.githubusercontent.com/8583900/94205189-a68f4200-feba-11ea-8c2d-789d1617ceea.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-25 13-51-15](https://user-images.githubusercontent.com/8583900/94269371-7be2cf00-ff36-11ea-95e0-a338694853e3.png)

![Screenshot from 2020-09-25 13-55-20](https://user-images.githubusercontent.com/8583900/94269600-c82e0f00-ff36-11ea-84f1-a973859a0c6c.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-29 15-16-40](https://user-images.githubusercontent.com/8583900/94570773-1ad53700-0267-11eb-9003-3b5768745470.png)

**Comment by Shimwell** [comment]
![Uploading Screenshot from 2020-09-29 15-27-33.png…]()

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-29 15-27-33](https://user-images.githubusercontent.com/8583900/94572025-79e77b80-0268-11eb-88da-828274539e9e.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-29 17-09-34](https://user-images.githubusercontent.com/8583900/94585086-6abbfa00-0277-11eb-91de-0b2548601587.png)
![Screenshot from 2020-09-29 17-14-54](https://user-images.githubusercontent.com/8583900/94585089-6c85bd80-0277-11eb-9be9-22befe19e86e.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-30 19-38-28](https://user-images.githubusercontent.com/8583900/94726067-a24ca400-0354-11eb-9a66-5aa0c6cd0f23.png)
![Screenshot from 2020-09-30 19-31-29](https://user-images.githubusercontent.com/8583900/94726081-a678c180-0354-11eb-93f2-98d4b4a6839e.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-30 19-43-36](https://user-images.githubusercontent.com/8583900/94726514-433b5f00-0355-11eb-94d2-06b2bba1ed4a.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-01 12-03-19](https://user-images.githubusercontent.com/8583900/94801594-2ac35700-03de-11eb-9545-3f2582d975e4.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-01 12-45-36](https://user-images.githubusercontent.com/8583900/94805330-213ced80-03e4-11eb-80b4-b162f2f7a565.png)
![Screenshot from 2020-10-01 12-38-22](https://user-images.githubusercontent.com/8583900/94805331-226e1a80-03e4-11eb-8623-3e6db0aa1489.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-01 13-10-03](https://user-images.githubusercontent.com/8583900/94807412-86461280-03e7-11eb-9854-ecf66489c262.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-01 13-12-01](https://user-images.githubusercontent.com/8583900/94807553-bab9ce80-03e7-11eb-9a2a-1b78a780b049.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-01 17-11-51](https://user-images.githubusercontent.com/8583900/94835218-51e34e00-0409-11eb-9372-0272c43a4844.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-01 20-28-21](https://user-images.githubusercontent.com/8583900/94854393-bd86e480-0424-11eb-9194-938a0c616b92.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-01 20-37-43](https://user-images.githubusercontent.com/8583900/94855159-fe332d80-0425-11eb-92a4-d1d43a066644.png)

**Comment by Shimwell** [comment]
This one was a little tricky, to include the plasma in the svg image I used a union operation

```
import paramak

plasma = paramak.Plasma(
    # default parameters
    rotation_angle=180,
    stp_filename="plasma_shape.stp",
    workplane='XY'
)


component = paramak.BlanketFP(
    plasma=plasma,
    thickness=[170,80, 80],
    stop_angle=250,
    start_angle=-70,
    offset_from_plasma=[30,70,30],
    rotation_angle=180,
    workplane='XY',
    stp_filename="blanket_constant_thickness_outboard_plasma.stp",
    union=plasma
)

component.export_svg('blanet_with_plasma.svg')
```
![Screenshot from 2020-10-01 22-51-56](https://user-images.githubusercontent.com/8583900/94867319-f0d36e80-0438-11eb-8516-7b8f2a7cc7ee.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-05 19-01-23](https://user-images.githubusercontent.com/8583900/95115392-511a2700-073d-11eb-9cb9-d6d2bec80e2c.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-05 18-48-56](https://user-images.githubusercontent.com/8583900/95115923-267c9e00-073e-11eb-898b-bafbb2626b02.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-07 13-50-49](https://user-images.githubusercontent.com/8583900/95333125-4037f580-08a4-11eb-956c-e608ab388bc8.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-07 20-38-37](https://user-images.githubusercontent.com/8583900/95379434-4b5b4780-08dd-11eb-8ac0-e3fce40efa90.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-09 12-42-32](https://user-images.githubusercontent.com/8583900/95579521-ba47b600-0a2d-11eb-9bdf-7f0415396978.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-12 22-06-33](https://user-images.githubusercontent.com/8583900/95790579-8f808a80-0cd7-11eb-83e1-872a98fe0bc8.png)
![Screenshot from 2020-10-12 22-08-39](https://user-images.githubusercontent.com/8583900/95790580-90b1b780-0cd7-11eb-944f-14fe290f8442.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-12 22-39-27](https://user-images.githubusercontent.com/8583900/95792839-2c452700-0cdc-11eb-9313-edfd2bfad5dc.png)
![Screenshot from 2020-10-12 22-41-39](https://user-images.githubusercontent.com/8583900/95792842-2d765400-0cdc-11eb-8a8a-e3a88e923bc0.png)
![Screenshot from 2020-10-12 22-42-58](https://user-images.githubusercontent.com/8583900/95792893-4ed74000-0cdc-11eb-9d19-c66cdb3a5ca3.png)

**Comment by Shimwell** [comment]
![Screenshot from 2020-10-25 09-39-14](https://user-images.githubusercontent.com/8583900/97103697-fde52580-16a5-11eb-935b-9bf2f9659419.png)
![Screenshot from 2020-10-25 09-18-33](https://user-images.githubusercontent.com/8583900/97103699-0178ac80-16a6-11eb-8e5a-ec3575d265fe.png)

**Comment by Shimwell** [comment]
![Uploading Screenshot from 2020-10-25 09-43-50.png…]()

**Comment by Shimwell** [comment]
This issue was getting quite large and slow to load, perhaps a better way to do this is to include the images in the PR.

Closing for now but can be reopened if needed
