### ISSUE TITLE
Doc: PoloidalFieldCoilCaseSet argument type error

### ISSUE THREAD

**Issue by RemiTheWarrior** [ukaea/paramak#330]
https://github.com/ukaea/paramak/blob/195a1cccf30d3ddfbe46f81018ac540f6868c03e/paramak/parametric_components/poloidal_field_coil_case_set.py#L10-L11

In the lines above, the arguments type should be list of float.

**Comment by Shimwell** [comment]
Thanks for reporting that @RemiTheWarrior just fixed it in https://github.com/ukaea/paramak/commit/495052d14e6a573a6b84373816a8211eb73f0b1e
