### ISSUE TITLE
Rotation angle and azimuthal placement angle differences

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#356]
I think this might have come up before but we noticed it again with #355

This screen shot shows cutters with azimuthal placement angles of 0, 45, 90, 180, 225 
Also included is a vacuum vessel with a rotation angle of 225

The angles don't line up and appear to be 90 degrees out of phase

![Screenshot from 2020-10-13 11-29-09](https://user-images.githubusercontent.com/8583900/95851051-9fd14d80-0d49-11eb-8c27-45ce18907ecd.png)

**Comment by RemDelaporteMathurin** [comment]
This issue is better described in #493
