### ISSUE TITLE
ading getter and setter to check input for the BallReactor

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#363]
The BallReactor class https://github.com/ukaea/paramak/blob/main/paramak/parametric_reactors/ball_reactor.py accepts some arguments from the user including:

- pf_coil_radial_thicknesses
- pf_coil_vertical_thicknesses

These two arguments should be a list and the type list should be checked on creation using a setter method like we have in other areas e.g. https://github.com/ukaea/paramak/blob/7f5acbd65f904a1ccb527e061a3b7e3f86b8a26f/paramak/shape.py#L229-L236

A getter will also need adding for each

This is nice and easy addition

**Comment by shen3443** [comment]
Is this still available? I'd like to help out if it is

**Comment by Shimwell** [comment]
Yep this is still available any help is welcome

**Comment by Shimwell** [comment]
Solved by @shen3443 , thanks for this contribution
