### ISSUE TITLE
Getting args for ITERtypeDivertorNoDome in docs

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#368]
The args for the ITERtypeDivertorNoDome in the docs are not showing up, but perhaps this is ok as it inherits.

https://paramak.readthedocs.io/en/latest/paramak.parametric_components.html#paramak.parametric_components.divertor_ITER_no_dome.ITERtypeDivertorNoDome

**Comment by RemDelaporteMathurin** [comment]
@Shimwell this is because in fact there isn't any argument specific to ITERtypeDivertorNoDome that doesn't live in ITERtypeDivertor

**Comment by RemDelaporteMathurin** [comment]
True. In the Dome version, if dome is False, then all these parameters (dome_height, dome_pos, dome_thickness) are ignored.

Perhaps the noDome version shouldn't exist to avoid confusion. The two images (dome and nodome) could illustrate the same ITERtypeDivertor class.
What do you think ?

**Comment by Shimwell** [comment]
I'm wondering if we have done it the wrong way around, perhaps we should inherit and extend instead of inherit and suppress

**Comment by RemDelaporteMathurin** [comment]
In my opinion it is a lot easier to inherit and remove since the method that creates the dome points take other points as argument
