### ISSUE TITLE
New test to check user input safeguards really work

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#373]
A recent PR added some nice getters and setters to the BallReactor class. https://github.com/ukaea/paramak/pull/371

These setters check that the user input pf_coil_radial_thickness and pf_coil_vertical_thickness are both lists which is great.

However the PR reduced the percent of code coverage our tests cover which we would like to fix and keep that badge bright green 

So a nice an easy PR which adds a couple of tests to https://github.com/ukaea/paramak/blob/main/tests/test_BallReactor.py

The tests should check that when a paramak.BallReactor is created with a non list value in either the pf_coil_vertical_thicknesses or pf_coil_radial_thicknesses that it raises a value error.

Something like this can be added to the test_BallReactor.py file, but we will also need a second test for the other setter
```
    def test_incorrect_args(self):
        """creates BallReactor with incorrect args to check that the errors are raised"""

        def test_incorrect_pf_coil_radial_thickness_type():
            """creates BallReactor with incorrect pf_coil_radial_thickness and checks a ValueError is raised"""


            test_reactor = paramak.BallReactor(
                inner_bore_radial_thickness=10,
                inboard_tf_leg_radial_thickness=30,
                center_column_shield_radial_thickness=60,
                divertor_radial_thickness=50,
                inner_plasma_gap_radial_thickness=30,
                plasma_radial_thickness=300,
                outer_plasma_gap_radial_thickness=30,
                firstwall_radial_thickness=30,
                blanket_radial_thickness=30,
                blanket_rear_wall_radial_thickness=30,
                elongation=2,
                triangularity=0.55,
                number_of_tf_coils=16,
                pf_coil_radial_thicknesses=50,
                pf_coil_vertical_thicknesses=[50, 50, 50, 50],
                pf_coil_to_rear_blanket_radial_gap=50,
                pf_coil_to_tf_coil_radial_gap=50,
                rotation_angle=360,
              )

        self.assertRaises(ValueError, test_incorrect_pf_coil_radial_thickness_type)
```

**Comment by RemDelaporteMathurin** [comment]
@Shimwell this has been fixed in #421
