### ISSUE TITLE
some required arguments missing

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#385]
Some classes do not remind the user of all of the required arguments. For example, the only required argument for ExtrudeStraightShape is distance. but this should also include 'points'.

**Comment by RemDelaporteMathurin** [comment]
Should points be defined at the `Shape()` level then ?

**Comment by billingsley-john** [comment]
To be a default argument, the parameter must be included in the __init__ of the class, so points should be added to the parametric_shapes' __init__

**Comment by RemDelaporteMathurin** [comment]
All parametric shapes inherit from Shape() where points is defaulting. So points do live in the parametric shapes as default.
