### ISSUE TITLE
Bad performance plasma plasmaboundaries

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [ukaea/paramak#389]
The plasmaboundaries class seems to be awfully slow at being created... This surely has something to do with the conversion of numpy arrays to list or something.

This must be solved if we want these to be scalable

**Comment by Shimwell** [comment]
Sounds like we need a python profiler

**Comment by Shimwell** [comment]
I think we might be calling the find_points method several times unnecessarily recreating the points

**Comment by RemDelaporteMathurin** [comment]
Would the hash_value for points added in #485 do the trick ?
