### ISSUE TITLE
Testing for extrude_both

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#392]
Simple tests need to be added to test the extrude_both function.
extrude_both=True = volume
extrude_both=False = volume * 0.5

**Comment by RemDelaporteMathurin** [comment]
I can maybe add them to #393

**Comment by Shimwell** [comment]
I saw this one which is similar as it checks for 0.5 of the volume.

https://github.com/ukaea/paramak/blob/b3ff4d99f737ee8ca4fea4866fdda18417204817/tests/test_parametric_shapes/test_ExtrudeStraightShape.py#L128-L141

But I am not sure if both actually changes the volume. I think both just shares the distance in two directions instead of one. If you want to check the volume you might have to get creative with some Boolean cuts

**Comment by Shimwell** [comment]
Ah yes sorry, you are right, both does certainly double the distance. Perhaps we need to update a few things then as I think our docstrings imply that the distance setting is the total extrusion distance

**Comment by Shimwell** [comment]
This code snippet might be hand for the tests

```
import paramak

cube1 = paramak.ExtrudeStraightShape(points=[(10, 10), (20, 10), (20, 20), (10,20)],
                                    distance=120,
                                    extrude_both=False,
                                    material_tag='cub_mat',
                                   azimuth_placement_angle=10)
cube2 = paramak.ExtrudeStraightShape(points=[(10, 40), (20, 40), (20, 30), (10,30)],
                                    distance=120,
                                    extrude_both=True,
                                    material_tag='cub_mat',
                                   azimuth_placement_angle=10)
print(cube1.volume)
print(cube2.volume)
my_reactor = paramak.Reactor(shapes_and_components=[cube1,cube2])
my_reactor.solid
```
![Screenshot from 2020-10-23 15-45-53](https://user-images.githubusercontent.com/8583900/97018405-06731a00-1547-11eb-930c-38b6f5c0bbd9.png)

**Comment by RemDelaporteMathurin** [comment]
I've added tests to #393

**Comment by RemDelaporteMathurin** [comment]
Tests have been added in #393
