### ISSUE TITLE
New paramaetric shape - casing for the TF coils

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#448]
We don't have any of the nice TF coils in the parametric reactors which is a shame as they look great.

However I think part of the reason for this is because they need cases to make them look correct.

To make a casing component from a TF coil it would be useful to expose a few more attributes of the coil. Perhaps a attribute called high_point could help build the casing.

Here is a sketch where the new varibles, attributes and geometry is in red, while the exisiting tf magnet geometry is in black

![Screenshot from 2020-11-09 11-59-42](https://user-images.githubusercontent.com/8583900/98538704-15660600-2283-11eb-86bd-070196770322.png)

Any thoughts?

**Comment by RemDelaporteMathurin** [comment]
I reckon the curved part has to have the same curvature as the magnet ?
