### ISSUE TITLE
InnerTfCoilsFlat being make with hole

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#462]
While running the [magnet set](https://github.com/ukaea/paramak/blob/main/examples/example_parametric_components/make_magnet_set.py) example i noticed that the InnerTfCoilsFlat was being made with a hole in it. This is probably something to do with the work plane changes but I'm not really sure. These should be continuous straight sections but something strange is happening here is the code to reproduce.

```python
import paramak

inner_tf_case = paramak.InnerTfCoilsFlat(
    height=1800,
    inner_radius=330,
    outer_radius=430,
    number_of_coils=8,
    gap_size=5,
    rotation_angle=180,
    azimuth_start_angle=(360 / 8) / 2.
)

inner_tf_case.solid
```

![Screenshot from 2020-11-11 15-19-02](https://user-images.githubusercontent.com/8583900/98830028-d4f8ba80-2431-11eb-8a20-72c67285c983.png)
![Screenshot from 2020-11-11 15-17-14](https://user-images.githubusercontent.com/8583900/98830032-d629e780-2431-11eb-9b99-f950fe81be46.png)

**Comment by RemDelaporteMathurin** [comment]
Have I messed something up with #428 ?

**Comment by RemDelaporteMathurin** [comment]
@Shimwell I am not sure it has to do with workplane but rather cutting wedges.

Removing the rotation_angle argument doesn't produce this bug : 

```python
import paramak

inner_tf_case = paramak.InnerTfCoilsFlat(
    height=1800,
    inner_radius=330,
    outer_radius=430,
    number_of_coils=8,
    gap_size=5,
    # rotation_angle=180,
)
inner_tf_case.solid
```
![image](https://user-images.githubusercontent.com/40028739/98846443-50b53000-244f-11eb-83f8-3ceed3ec9438.png)

**Comment by RemDelaporteMathurin** [comment]
@Shimwell it's confirmed:
```
import paramak

inner_tf_case = paramak.InnerTfCoilsFlat(
    height=1800,
    inner_radius=330,
    outer_radius=430,
    number_of_coils=8,
    gap_size=5,
    rotation_angle=180,
)
inner_tf_case.solid
inner_tf_case.export_stl('out.stl')

cutting_wedge = paramak.CuttingWedgeFS(inner_tf_case)
cutting_wedge.export_stl('cutting_wedge.stl')
```
![image](https://user-images.githubusercontent.com/40028739/98846961-fa94bc80-244f-11eb-8460-4c138aeda8c3.png)
![image](https://user-images.githubusercontent.com/40028739/98846980-fff20700-244f-11eb-9388-bf867e5c0490.png)

**Comment by RemDelaporteMathurin** [comment]
Problem is CuttingWedgeFS uses the shape workplane (which is in this case the XY plane).
I think the CuttingWedge workplane should be computed from the rotation axis rather than from the shape workplane.

The following allows to have the correct orientation, but the dimensions aren't correct.

```python
    def get_workplane(self):
        workplanes = ["XY", "YZ", "XZ"]
        for wp in workplanes:
            if self.rotation_axis in wp:
                return wp
```

**Comment by Shimwell** [comment]
Ah great detective work
