### ISSUE TITLE
reactor export_stl error raising

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#481]
A check exists in Reactor.export_stl() which checks that .stl_filenames only contains unique filenames. However, if different components are created from the same parametric component (like the ball reactor firstwall, blanket and blanket rear), identical stl filenames are appended to .stl_filenames and an error is raised when we try to export_stl.

**Comment by billingsley-john** [comment]
In parametric reactor constrution, stl_filename should also be specified when each component is created to prevent this

**Comment by Shimwell** [comment]
good spot there

**Comment by billingsley-john** [comment]
Resolved in #482
