### ISSUE TITLE
Can't build image on Windows

### ISSUE THREAD

**Issue by RemDelaporteMathurin** [ukaea/paramak#494]
Running `docker build .` on Windows throws an error:

```
#7 3.354 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c apt-get install -y libgl1-mesa-glx]: runc did not terminate sucessfully
```

Adding `apt-get update` to the line below seems to solve it.
https://github.com/ukaea/paramak/blob/87008817a9f89d3bf0308f79f1b14e8fc878502f/Dockerfile#L18

**Comment by Shimwell** [comment]
I think the dockerfile was updated recently. This new one might work better https://github.com/ukaea/paramak/blob/develop/Dockerfile

But I think you can also download the image like this

docker pull ukaea/paramak

And run it like this for terminal access
sudo docker run -it paramak
Or like this for a jupyter notebook
docker run -p 8888:8888 paramak

**Comment by Shimwell** [comment]
ah perhaps I need to change the tag name a bit for the docker pull to work. Will do so soon

**Comment by Shimwell** [comment]
#501 contains so details for the readme and the installation section of the docs

**Comment by RemDelaporteMathurin** [comment]
> But I think you can also download the image like this
> 
> `docker pull ukaea/paramak:dev`
> 
> And run it like this for terminal access
> `docker run -it ukaea/paramak:dev`
> Or like this for a jupyter notebook
> `docker run -p 8888:8888 ukaea/paramak:dev`

The idea was to see if #445 could be fixed by using the nightly version of cadquery. Therefore, neither the ukaea/paramak nor the openmcworkshop/paramak could be used since they both use cadquery=2 version.

**Comment by Shimwell** [comment]
Ah got you, ok I can change both images to use cadquery master

**Comment by RemDelaporteMathurin** [comment]
Building with the current Dockerfile on Windows raises:
```
failed to solve with frontend dockerfile.v0: failed to build LLB: executor failed running [/bin/sh -c conda install -c conda-forge -c cadquery cadquery=master &&     conda install jupyter -y --quiet &&     conda clean -afy]: runc did not terminate sucessfully
```

**Comment by Shimwell** [comment]
Ah my fault, I can fix this

**Comment by Shimwell** [comment]
I think this might be fixed with the latest dockerfile that is now on main and develop branch

**Comment by RemDelaporteMathurin** [comment]
I tried yesterday and the same error occured

**Comment by RemDelaporteMathurin** [comment]
I can now build the image with windows. Closing this as it must have been solved along the way
