### ISSUE TITLE
additional argument for port cutters

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#521]
The PortCutterRectangular and PortCutterCircular are great and make nice shapes.

One optional upgrade for us to consider is allowing them to have a inner raduis where the shape starts.

This would be useful when they are used to make a port in the outboard firstwall. One schenarios is users make a firstwall and then want to cut a port. Unfortunately the firstwall will be cut on the inboard and outboard. This is because the PortCutters start from 0 on the x axis.

Another argument for the inner radius could solve this use case problem and make the components even more useful.

**Comment by RemDelaporteMathurin** [comment]
To be clear, you'd like to reproduce these extrusions on the VV ?
![image](https://user-images.githubusercontent.com/40028739/99545018-3cc07f80-29b5-11eb-8c29-32df820333bd.png)

Is so, I think more than additional arguments, we need new shapes.

**Comment by Shimwell** [comment]
I was planning on doing a large rectangle port then cut away a small rectangle.

To begin with I was just going to use it on relatively flat surfaces so I can probably get away with just a modified port cutter shape that accepts an inner_radius argument (defaults to 0)

In the longer term the curve of the vessel would be good to use as a cutter. The outer solid can be obtained using a cadquery selector (nearest point or perhaps largest volume)

**Comment by Shimwell** [comment]
![Screenshot from 2020-11-19 17-09-52](https://user-images.githubusercontent.com/8583900/99699691-2506fb00-2a8a-11eb-91a5-18994e1115ce.png)

**Comment by P-S-S-M** [comment]
Port within the paramak such as in the fantastic drawing above would be very useful. I think it will allow people to visualise the loss of breeding volume due to equatorial ports and look at their impact in simplified analysis.

Sam

**Comment by billingsley-john** [comment]
Perhaps a combination of a cut and an intersect would achieve the desired port wholly within the correct outboard component
