### ISSUE TITLE
on the circeci the deletion of the docker file must always run even if the tests fail

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#531]
On the circeci the deletion of the docker file must always run even if the tests fail. 

This can be done with the When keyword instead of the required keyword that is currently used

**Comment by RemDelaporteMathurin** [comment]
I think that the When keyword is for steps, we want to apply it for jobs. I haven't found the equivalent yet

**Comment by RemDelaporteMathurin** [comment]
I'm fixing this in #507
