### ISSUE TITLE
adding htc reactor example to tests and remove duplicates

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#569]
I noticed a small error in the htc reactor, the EFCCu_coils_6 variable has been defined twice accidentally.

I can fix this when I add tests to that example in new PR

https://github.com/ukaea/paramak/blob/1d59219ea45e9d7d0f992d88c11908d5e077a365/examples/example_parametric_reactors/htc_reactor.py#L130

**Comment by RemDelaporteMathurin** [comment]
@Shimwell can this be closed now ?
