### ISSUE TITLE
Enhancement: analytical expression for plasma object

### ISSUE THREAD

**Issue by RemiTheWarrior** [ukaea/paramak#59]
If I understood correctly, the component plasma is created from 2 arcs.

Why not using the actual analytical expression for the plasma boundary ? (based on elongation, triangularity, minor and major radii)

![image](https://user-images.githubusercontent.com/40028739/87244882-f83e3980-c440-11ea-9ec1-82fa105e7b58.png)

This would give a smoother and perhaps more accurate shape ?

**Comment by Shimwell** [comment]
That looks like a nicer method. I guess that makes supporting double and single null plasmas easier as well.

The plasma is one of the oldest shapes so it is probably can be done in a better way.

It would be handy for other shapes that try to keep a constant offset if the X point (X and Z) coordinates are also available from the plasma objects

**Comment by RemiTheWarrior** [comment]
The trick is to find the correct equations. See [this paper](https://fire.pppl.gov/ARIES_AT_Equilibrium_kessel.pdf)

**Comment by Shimwell** [comment]
Equation 7 looks good

**Comment by RemiTheWarrior** [comment]
Is it "double null friendly" ?

**Comment by RemiTheWarrior** [comment]
Done in #64
