### ISSUE TITLE
improved images that show parameters

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#60]
The images for parametric components, shapes and reactors are nice but they don't show how the parameters change the shape of the models

One option is to make svg images using the exportsvg method then convert this to a png then add annotations to this image using  latex

I had a quick go at this to see how it looks, perhaps this or something like this could be something we consider adding to the documentation in the future.

Currently the workplane has to be set to 'XY' as the exportsvg has no camera position argument.

![Screenshot from 2020-07-12 14-31-11](https://user-images.githubusercontent.com/8583900/87248024-14e16e00-c44f-11ea-8697-bb227ecfd448.png)

![Screenshot from 2020-07-12 14-30-24](https://user-images.githubusercontent.com/8583900/87248026-16129b00-c44f-11ea-9a7b-349f1a035872.png)

**Comment by billingsley-john** [comment]
I think this would be a good addition, especially for the documentation

**Comment by RemiTheWarrior** [comment]
@Shimwell good idea, perhaps add the origin location.

**Comment by Shimwell** [comment]
![Screenshot from 2020-07-13 13-33-51](https://user-images.githubusercontent.com/8583900/87305125-df4f8a00-c50d-11ea-9984-b56799fc0cc3.png)

Added a Z axis and rotation angle

**Comment by Shimwell** [comment]
I have been using https://www.mathcha.io/ to make Latex images and it speeds up the process quite a lot

**Comment by Shimwell** [comment]
The documentation now has lots of parametric components and quite a lot have nice diagrams

- [x] BlanketConstantThicknessArcH
- [x] BlanketConstantThicknessArcV
- [ ] BlanketFP
- [x] CenterColumnShieldCylinder
- [x] CenterColumnShieldHyperbola
- [x] CenterColumnShieldFlatTopHyperbola
- [x] CenterColumnShieldFlatTopCircular
- [ ] CenterColumnShieldPlasmaHyperbola
- [ ] ITERtypeDivertor
- [ ] DivertorITERNoDome
- [x] InnerTfCoilsCircular
- [x] InnerTfCoilsFlat
- [ ] PoloidalFieldCoil
- [ ] PoloidalFieldCoilCaseFC
- [ ] PoloidalFieldCoilCase
- [ ] Plasma
- [ ] PlasmaFromPoints
- [ ] ToroidalFieldCoilRectangle
- [ ] ToroidalFieldCoilCoatHanger

**Comment by Shimwell** [comment]
![Screenshot from 2020-09-25 14-32-58](https://user-images.githubusercontent.com/8583900/94273259-1265bf00-ff3c-11ea-95ed-89123be3bd16.png)

**Comment by Shimwell** [comment]
I've added a few more yesterday, but we have more components now.

Easy ones to do are the PoloidalFieldCoil and the Plasma

And I somehow keen forgetting to add the origin even with the reminders, sorry about that :-)

**Comment by Shimwell** [comment]
Plasma and Plasma from points done

**Comment by Shimwell** [comment]
ToroidalFieldCoilTripleArc (thanks @RemiTheWarrior), PoloidalFieldCoilCase and PoloidalFieldCoil all done

**Comment by Shimwell** [comment]
Closing this issue for the same reasons as #32 . Please add images to the PR instead
