### ISSUE TITLE
Self.face property for shapes

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#619]
When making a extruded, rotated or sweep shape we first make a closed face (cq wire)

This face could perhaps be set as an attribute so that users can access it. 

It could be useful for making a 2D image of the reactor. It could also be useful when making an offset of the shape.

**Comment by billingsley-john** [comment]
If a self.wire attribute is being added as part of the solid creation, should self.face point to the self.wire attribute?

**Comment by Shimwell** [comment]
the self.wire property has been added in #626 and is now in develop
