### ISSUE TITLE
Adding  distance and thickness labels to diagram for ToroidalFieldCoilPrincetonD

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#621]
The diagram for the ToroidalFieldCoilPrincetonD is missing the distance and thickness arguments.

Perhaps if these labels are added then the diagram could be redone in the draw.io to produce a nicer svg image

![tf](https://user-images.githubusercontent.com/8583900/94529559-cd8aa280-0231-11eb-9919-48d3c642a5d7.png)

**Comment by billingsley-john** [comment]
![Screenshot from 2020-12-08 12-37-55](https://user-images.githubusercontent.com/56687624/101485287-dc3cb680-3952-11eb-8b70-4ef40940ef98.png)

**Comment by Shimwell** [comment]
Nice improvements

**Comment by Shimwell** [comment]
This has now been merged into develop via #625
