### ISSUE TITLE
New parametric component for a rotated wedge 

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#630]
Just wondering if another parametric shapes should be added for a rotatable wedge shape.

This could be useful for cutting ports and other channels

Sketched out a few of the parameters that could be used to make the component

![Screenshot from 2020-12-10 22-35-53](https://user-images.githubusercontent.com/8583900/101838199-216e0d80-3b38-11eb-8d2c-0fcaba638b40.png)

**Comment by RemDelaporteMathurin** [comment]
I don't really get what "angle" stands for here. What's the rotation axis ?

**Comment by Shimwell** [comment]
I think by default rotation axis is from the pivot point downwards on the z axis

**Comment by Shimwell** [comment]
I've made a PR for this #633 it has some images the perhaps explain the shape a bit more

**Comment by Shimwell** [comment]
closing as this have been merged into develop

**Comment by RemDelaporteMathurin** [comment]
@Shimwell does this belong to 0.2 instead of 0.3 ?
