### ISSUE TITLE
Parmentic shape for hexagons

### ISSUE THREAD

**Issue by Shimwell** [ukaea/paramak#705]
As hexagons appear to be important shapes in both fusion (HPCB) blanket and fission reactors we should consider adding a parametric shape for them.

In the mean time they can be made using the StraightShape classes

![Screenshot from 2020-12-02 15-37-21](https://user-images.githubusercontent.com/8583900/106464315-67888300-6490-11eb-8a64-80672a83316c.png)

**Comment by Shimwell** [comment]
This issue is being solved in this #706

**Comment by shimwell** [comment]
This has been merged into develop with #706
