### ISSUE TITLE
reactor workplane cannot be changed

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#739]
Currently, reactor workplane cannot be specified. It is defaulted to XY - should this be controllable?

**Comment by shimwell** [comment]
Any chance you could provide an example as I didn't even think reactors had workplaces.

**Comment by billingsley-john** [comment]
Apologies - this wasn't described very well. Currently, reactors do not have a workplane option so their orientation is dictated by the default workplanes of all shapes and components that make up the reactor. Currently, export_svg defaults to a workplane which views reactors from the top-down, but the reactor workplane can't be changed. However, instead of adding workplane control to the reactors, perhaps this issue is better resolved in the export_svg function.
