### ISSUE TITLE
TF Coil Overlap Issue

### ISSUE THREAD

**Issue by katie-taylor** [ukaea/paramak#780]
With inner leg true, and anything more than 2 coils, code crashes.

Suspect its down to coil overlap.

```Python
tf_coils = paramak.ToroidalFieldCoilRectangle(
                    horizontal_start_point = [10, 886.4],
                    vertical_mid_point = [865.3, 0],
                    thickness = 55.4,
                    distance = 55.4,
                    number_of_coils = 12,
                    with_inner_leg = True)
tf_coils.show
```

**Comment by billingsley-john** [comment]
Image of failing shape construction

![Screenshot from 2021-03-17 12-20-27](https://user-images.githubusercontent.com/56687624/111466826-a9f1e080-871b-11eb-9f54-32b9b93634b2.png)
