### ISSUE TITLE
Incorrect ToroidalFieldCoilTripleArc R1 variable

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#785]
Documentation suggests R1 is the distance to the rear/outer of the inboard leg of the TF coil. However, upon construction, this parameter is the distance to the front/inner of the inboard leg. Not sure whether the documentation image or construction is incorrect.

`
shape = p.ToroidalFieldCoilTripleArc(
    R1=40,
    h=200,
    radii=(70, 100),
    coverages=(60, 60),
    thickness=20,
    distance=40,
    number_of_coils=1
)
`

Notice x-value for rear/outer points of inboard leg = 20, when should be 40 (according to documentation)

![Screenshot from 2021-03-25 12-31-08](https://user-images.githubusercontent.com/56687624/112473247-041b2300-8d66-11eb-9c42-b26dc3b35938.png)

![Screenshot from 2021-03-25 12-43-35](https://user-images.githubusercontent.com/56687624/112474600-c15a4a80-8d67-11eb-8ee7-7573928ddc1e.png)

**Comment by shimwell** [comment]
Nice find John. I guess it is useful to have the variable set to that inner distance, perhaps we should changed the code so that the thickness is added to R1 when finding the points.
