### ISSUE TITLE
ToroidalFieldCoilPrincetonD R1 variable

### ISSUE THREAD

**Issue by billingsley-john** [ukaea/paramak#787]
Currently, the R1 variable of this class corresponds to the distance to the furthest surface of the inner leg (from origin) - (i.e. the 'inner' surface of the inner leg from inside the coil). Outlined in #786, R1 should correspond to the nearest surface of the inner leg (from origin) - (i.e. the 'outer' surface of the inner leg from inside the coil), to be consistent with ToroidalFieldCoilTripleArc

**Comment by shimwell** [comment]
Thanks for discovering this, I guess there are a few things like this that go silently unnoticed for a while

**Comment by billingsley-john** [comment]
See #789

**Comment by billingsley-john** [comment]
Resolved in #789
