### ISSUE TITLE
Contributions: templates for PR and bug report

### ISSUE THREAD

**Issue by RemiTheWarrior** [ukaea/paramak#85]
A low effort addition that will facilitate contribution (imho)

**Comment by Shimwell** [comment]
Any preference to the template used for PR

Here are a few to choose from 

https://github.com/devspace/awesome-github-templates#rocket-templates-for-pull-requests

**Comment by RemiTheWarrior** [comment]
https://github.com/appium/appium/blob/master/.github/PULL_REQUEST_TEMPLATE.md

I like this one. I think the check list is the most important thing

**Comment by Shimwell** [comment]
We might have to remove a few check boxes as we don't have a contribution guide or a cli.

I can see how it would help keep the code tidy.

Only downside is that it slows down commits and might deter contributions. But people can always ignore the template if they are in a rush.

I can put in a PR for the template using the template just to get some practice

**Comment by RemiTheWarrior** [comment]
@Shimwell sure some aren't usefull. Well as it's not mandatory, it won't be limiting. But yeah it helps (even for internal developpers) to keep in mind the things to do (like docs) before merging

**Comment by RemiTheWarrior** [comment]
@Shimwell current vs new behaviour can also be a nice section. It's up to you

**Comment by Shimwell** [comment]
PR template is now in develop. It will work once it gets to the default branch (main). @billingsley-john is merging into main today so it should be up and running soon.

Thanks for the suggestion
